### ISSUE TITLE
Live照片兼容问题

### ISSUE THREAD

**Issue by ghjhtd** [wszqkzqk/live-photo-conv#7]
1.实测发现，任意图片加视频合成的Live图，在Pc端能识别，下载到手机后不能识别。

2.如果合成的图片使用从手机端解压出来的一张图片，则Pc端能识别，下载到手机后能识别。

3.使用exiftool解析对比元数据发现1中生成的Live图，缺少了很多元信息。

4.要生成手机端能识别的Live图，对于要合成的图片，需要拷贝一份手机端原始Live图解压出来图片的元数据。

**Comment by wszqkzqk** [comment]
> 3.使用exiftool解析对比元数据发现1中生成的Live图，缺少了很多元信息。

“很多信息”是什么信息。目前很多手机的解析器确实是要检测exif元数据才会识别为动态照片，但是**本工具显然不能编造一份与拍摄参数有关的exif**。这一问题你应该向手机厂商反馈而不是向我反馈。

**Comment by wszqkzqk** [comment]
> 厂商照片相关的一些元数据，因为白天遇到了生成的动态照片在pc端能展示为动态照片，但是在手机端识别不了的问题。想着其他人也可能遇到这个问题，为了让这个项目变得更好，所以提了一条记录，方便以后有相关需求的人了解。

这你只能向厂商反馈，本项目不打算编造exif记录的拍摄参数。

**Comment by wszqkzqk** [comment]
这不属于可以解决的“兼容问题”，如果你认为可以，你可以发起PR，合理的话我也可以合并

**Comment by ghjhtd** [comment]
我的措辞有点问题，这个不是个问题，应该算是记录一下实现某种特殊场景展示的一种方式。想要将通过普通照片合成的live图在手机端展示时，可以通过一张该手机拍的Live图片作为模板，将模板解析出的照片的元数据copy到普通照片中，现有脚本就可以实现

**Comment by ghjhtd** [comment]
就是用的copy-img-meta，大佬说的太有道理了。因为我的目标是需要手机端识别合成的动态照片，属于没有办法的办法，只能这样弄了。这个工具很棒，网上找到的唯一一个合成工具，感谢大佬的开源，编译时遇到问题也多亏大佬帮助，回复消息快，效率高，真心感谢大佬帮助❤️


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月19日(周二) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wszqkzqk/live-photo-conv] Live照片兼容问题 (Issue #7)




  
将模板解析出的照片的元数据copy到普通照片中
  
你是否发现除了live-photo-conv外我本来就额外提供了一个copy-img-meta，你可以自己衡量这是用来做什么的，以及我为什么要开发这个工具。
  
可以通过一张该手机拍的Live图片作为模板
  
不同的照片的拍摄信息显然不一样，这样复制的信息对于新的照片是错误的。只能说你原来的静态照片最好有手机厂商认可的元数据，否则总会有问题。至少说我作为开发者我无法推荐复制别的照片的元数据的做法，至于你自己根据自己需要如何处理则同样是需要你自己衡量，不在此考虑范畴。
