### ISSUE TITLE
编译环境问题

### ISSUE THREAD

**Issue by liuzhenghang** [wszqkzqk/live-photo-conv#9]
在Windws的 MSYS2 UCRT64 环境下编译，已安装依赖，遇到可能是项目依赖上的问题？
[log.txt](https://github.com/user-attachments/files/18036652/log.txt)

**Comment by wszqkzqk** [comment]
是否安装了gexiv2

**Comment by wszqkzqk** [comment]
MSYS2的话可以直接用我的[构建脚本](https://gist.github.com/wszqkzqk/052a48feb5b84a469ee43231df91dc9d)

**Comment by liuzhenghang** [comment]
已经安装了gexiv2（pacman -S mingw-w64-x86_64-gexiv2）
我尝试了用构建脚本，不过依然是同样的错误
[logs.log](https://github.com/user-attachments/files/18036867/logs.log)

**Comment by liuzhenghang** [comment]
把ucrt重装了一遍，改用构建脚本
这次不一样了
![image](https://github.com/user-attachments/assets/8f5d4496-4ca5-4844-8961-c63355d0aee1)

**Comment by liuzhenghang** [comment]
是不是pacman -S base-devel，我用的全新环境，确实没有装

**Comment by wszqkzqk** [comment]
> 是不是pacman -S base-devel，我用的全新环境，确实没有装

需要安装，参见：https://www.msys2.org/dev/new-package/

**Comment by liuzhenghang** [comment]
第一关算是过了，目前提示需要gcc，我需要
pacman -S gcc吗

![image](https://github.com/user-attachments/assets/8f074993-64c1-4540-87ec-2009b1a23f40)

**Comment by wszqkzqk** [comment]
> 第一关算是过了，目前提示需要gcc，我需要 pacman -S gcc吗
> 
> ![image](https://private-user-images.githubusercontent.com/42809504/393224872-8f074993-64c1-4540-87ec-2009b1a23f40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODM2MTMsIm5iZiI6MTczMzQ4MzMxMywicGF0aCI6Ii80MjgwOTUwNC8zOTMyMjQ4NzItOGYwNzQ5OTMtNjRjMS00NTQwLTg3ZWMtMjAwOWIxYTIzZjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDExMDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNmMzMzkwY2E2NTRmNjVmYzdiMGYxODIyMWYyNmE4NDk5YjRkMzM3OTljY2E4ODEzYmNlYTlmNGRiYzVmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m1QIVXWDjPgtO7zOwz-hjBy92iVkH7Bzq8nPML95gmY)

对于UCRT64，还需要[mingw-w64-ucrt-x86_64-toolchain](https://packages.msys2.org/groups/mingw-w64-ucrt-x86_64-toolchain)

**Comment by wszqkzqk** [comment]
`base-devel`和对应环境的`toolchain`都是默认你要构建包就已经安装了的，所以不写进`makedepends`里面。

**Comment by liuzhenghang** [comment]
感谢，编译完成了，由于第一次接触这个，多有请教🙏
